import { db } from "@/server/db";
import { clientPhones, clients, osintResults } from "@/server/db/schema";
import { eq, ilike } from "drizzle-orm";
import { normalizePhone } from "@/lib/utils";

export type PhoneProvider = "local-intelligence" | "rapidapi-truecaller";

export interface PhoneLookupResult {
  phone: string;
  normalized: string;
  name: string | null;
  risk_score: number;
  spam: boolean;
  notes: string;
  source: "internal" | "external" | "mixed" | "fallback";
  provider: PhoneProvider;
  confidenceScore: number;
  tags: string[];
  country: string | null;
  carrier: string | null;
  whatsappAvailable: boolean;
  telegramAvailable: boolean;
  aliases: string[];
  raw?: unknown;
}

function detectEgyptCarrier(normalized: string): string | null {
  const local = normalized.replace(/^\+?2/, "");
  if (local.startsWith("010")) return "Vodafone";
  if (local.startsWith("011")) return "Etisalat";
  if (local.startsWith("012")) return "Orange";
  if (local.startsWith("015")) return "WE";
  return null;
}

function buildLocalIntelligence(phone: string, normalized: string): Omit<PhoneLookupResult, "source"> {
  const carrier = detectEgyptCarrier(normalized);
  const digits = normalized.replace(/\D/g, "");
  const suspicious = /0000|1111|1234|9999/.test(digits);
  const manyRepeats = /(\d)\1{4,}/.test(digits);

  let risk = 5;
  if (!carrier) risk += 10;
  if (suspicious) risk += 30;
  if (manyRepeats) risk += 20;
  if (digits.length < 11) risk += 15;
  const riskScore = Math.max(0, Math.min(100, risk));

  const confidenceBase = carrier ? 78 : 60;
  const confidenceScore = Math.max(0, Math.min(100, confidenceBase - (riskScore > 50 ? 10 : 0)));

  const tags: string[] = [];
  if (carrier) tags.push(`carrier:${carrier.toLowerCase()}`);
  if (suspicious || manyRepeats) tags.push("pattern-risk");
  if (digits.startsWith("20")) tags.push("egypt");

  const aliasSeed = digits.slice(-4);
  const aliases = aliasSeed ? [`EG-${aliasSeed}`, `User-${aliasSeed}`] : [];

  return {
    phone,
    normalized,
    name: null,
    risk_score: riskScore,
    spam: riskScore >= 60,
    notes: "Generated by local heuristics",
    provider: "local-intelligence",
    confidenceScore,
    tags,
    country: "Egypt",
    carrier,
    whatsappAvailable: digits.length >= 11,
    telegramAvailable: digits.length >= 11,
    aliases,
  };
}

async function tryRapidApiLookup(phone: string): Promise<Partial<PhoneLookupResult> | null> {
  const rapidApiKey = process.env.RAPIDAPI_KEY?.trim();
  if (!rapidApiKey) return null;

  try {
    const res = await fetch("https://truecaller-data2.p.rapidapi.com/search", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-rapidapi-key": rapidApiKey,
        "x-rapidapi-host": "truecaller-data2.p.rapidapi.com",
      },
      body: JSON.stringify({ phone }),
      cache: "no-store",
    });

    const text = await res.text();
    if (!res.ok) return null;
    const raw = text ? JSON.parse(text) : {};
    const top = (raw as any)?.data || (raw as any)?.result || raw;

    return {
      name: typeof top?.name === "string" ? top.name : null,
      risk_score: Number.isFinite(Number(top?.spamScore)) ? Number(top.spamScore) : undefined,
      confidenceScore: Number.isFinite(Number(top?.confidenceScore)) ? Number(top.confidenceScore) : undefined,
      tags: Array.isArray(top?.tags) ? top.tags : undefined,
      whatsappAvailable: Boolean(top?.whatsapp || top?.isWhatsapp),
      telegramAvailable: Boolean(top?.telegram || top?.isTelegram),
      provider: "rapidapi-truecaller",
      source: "external",
      raw,
    };
  } catch {
    return null;
  }
}

export async function phoneLookup(phone: string): Promise<PhoneLookupResult> {
  const normalized = normalizePhone(phone);
  if (!normalized || normalized.length < 7) {
    return {
      ...buildLocalIntelligence(phone, normalizePhone(`+20${phone}`) || String(phone)),
      source: "fallback",
      notes: "Invalid format handled by fallback intelligence",
    };
  }

  const phonePattern = `%${normalized.slice(-10)}%`;

  const internal = await db
    .select({ clientName: clients.name, osintSummary: osintResults.summary })
    .from(clientPhones)
    .leftJoin(clients, eq(clients.id, clientPhones.clientId))
    .leftJoin(osintResults, eq(osintResults.clientId, clientPhones.clientId))
    .where(ilike(clientPhones.phone, phonePattern))
    .limit(1)
    .then((rows) => rows[0] || null);

  const local = buildLocalIntelligence(phone, normalized);
  const external = await tryRapidApiLookup(normalized);

  const merged: PhoneLookupResult = {
    ...local,
    name: external?.name || internal?.clientName || null,
    risk_score: Number.isFinite(Number(external?.risk_score)) ? Number(external?.risk_score) : local.risk_score,
    confidenceScore: Number.isFinite(Number(external?.confidenceScore)) ? Number(external?.confidenceScore) : local.confidenceScore,
    tags: Array.from(new Set([...(local.tags || []), ...((external?.tags as string[]) || [])])),
    whatsappAvailable: typeof external?.whatsappAvailable === "boolean" ? external.whatsappAvailable : local.whatsappAvailable,
    telegramAvailable: typeof external?.telegramAvailable === "boolean" ? external.telegramAvailable : local.telegramAvailable,
    provider: (external?.provider as PhoneProvider) || "local-intelligence",
    source: external ? (internal ? "mixed" : "external") : (internal ? "mixed" : "fallback"),
    aliases: local.aliases,
    raw: external?.raw,
  };

  return merged;
}
