import { db } from "@/server/db";
import { clientPhones, clients, osintResults } from "@/server/db/schema";
import { eq, ilike } from "drizzle-orm";
import { normalizePhone } from "@/lib/utils";

export type PhoneProvider = "local-intelligence";

export interface PhoneLookupResult {
  phone: string;
  normalized: string;
  name: string | null;
  risk_score: number;
  spam: boolean;
  notes: string;
  source: "internal" | "external" | "mixed" | "fallback";
  provider: PhoneProvider;
  confidenceScore: number;
  tags: string[];
  country: string | null;
  carrier: string | null;
  whatsappAvailable: boolean;
  telegramAvailable: boolean;
  aliases: string[];
  raw?: unknown;
}

function detectEgyptCarrier(normalized: string): string | null {
  const local = normalized.replace(/^\+?2/, "");
  if (local.startsWith("010")) return "Vodafone";
  if (local.startsWith("011")) return "Etisalat";
  if (local.startsWith("012")) return "Orange";
  if (local.startsWith("015")) return "WE";
  return null;
}

function buildLocalIntelligence(phone: string, normalized: string): Omit<PhoneLookupResult, "source"> {
  const carrier = detectEgyptCarrier(normalized);
  const digits = normalized.replace(/\D/g, "");
  const suspicious = /0000|1111|1234|9999/.test(digits);
  const manyRepeats = /(\d)\1{4,}/.test(digits);

  let risk = 5;
  if (!carrier) risk += 10;
  if (suspicious) risk += 30;
  if (manyRepeats) risk += 20;
  if (digits.length < 11) risk += 15;
  const riskScore = Math.max(0, Math.min(100, risk));

  const confidenceBase = carrier ? 78 : 60;
  const confidenceScore = Math.max(0, Math.min(100, confidenceBase - (riskScore > 50 ? 10 : 0)));

  const tags: string[] = [];
  if (carrier) tags.push(`carrier:${carrier.toLowerCase()}`);
  if (suspicious || manyRepeats) tags.push("pattern-risk");
  if (digits.startsWith("20")) tags.push("egypt");

  const aliasSeed = digits.slice(-4);
  const aliases = aliasSeed ? [`EG-${aliasSeed}`, `User-${aliasSeed}`] : [];

  return {
    phone,
    normalized,
    name: null,
    risk_score: riskScore,
    spam: riskScore >= 60,
    notes: "Generated by local heuristics",
    provider: "local-intelligence",
    confidenceScore,
    tags,
    country: "Egypt",
    carrier,
    whatsappAvailable: digits.length >= 11,
    telegramAvailable: digits.length >= 11,
    aliases,
  };
}

export async function phoneLookup(phone: string): Promise<PhoneLookupResult> {
  const normalized = normalizePhone(phone);
  if (!normalized || normalized.length < 7) {
    return {
      ...buildLocalIntelligence(phone, normalizePhone(`+20${phone}`) || String(phone)),
      source: "fallback",
      notes: "Invalid format handled by fallback intelligence",
    };
  }

  const phonePattern = `%${normalized.slice(-10)}%`;

  const internal = await db
    .select({ clientName: clients.name, osintSummary: osintResults.summary })
    .from(clientPhones)
    .leftJoin(clients, eq(clients.id, clientPhones.clientId))
    .leftJoin(osintResults, eq(osintResults.clientId, clientPhones.clientId))
    .where(ilike(clientPhones.phone, phonePattern))
    .limit(1)
    .then((rows) => rows[0] || null);

  const local = buildLocalIntelligence(phone, normalized);
  const merged: PhoneLookupResult = {
    ...local,
    name: internal?.clientName || null,
    source: internal ? "mixed" : "fallback",
    aliases: local.aliases,
    tags: Array.from(new Set([...(local.tags || []), ...(internal?.osintSummary ? ["has-internal-osint"] : [])])),
    notes: internal?.osintSummary ? `Local intelligence + internal OSINT context: ${internal.osintSummary}` : local.notes,
  };

  return merged;
}
